[package]
name = "sbomforge"
version = "0.2.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8.19"
clap = { version = "4.0", features = ["derive"] }
pyo3 = { version = "0.22.3", features = ["extension-module"] }
regex = "1.11.0"
